Tindeggle/urls.py
from django.contrib import admin
from django.urls import path, include
from match.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView, name='HomeView'),
    path('createProfile/', CreateProfileView, name='createProfile'),
    path('addInterests/', AddInterestsView, name='addInterests'),
    path('editInterests/', EditInterestsView, name='editInterests'),
    path('profileSearch/', ProfileSearchView, name='profileSearch'),
    path('profileView/<str:username>/', ProfileView, name='profileView'),
    path('chat/<str:username1>/<str:username2>/', ChatView, name='chatView'),
    path('startChat/', StartChatView, name='startChat'),
    path('randomChat/<int:id>', RandomChatView, name='RandomChat'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

match/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import *
from django.forms import ModelForm
from django.forms import TextInput, Textarea, DateInput

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=500, blank=True)
    ppic1 = models.ImageField()
    ppic2 = models.ImageField(blank=True)
    ppic3 = models.ImageField(blank=True)
    ppic4 = models.ImageField(blank=True)
    ppic5 = models.ImageField(blank=True)
    ppic6 = models.ImageField(blank=True)
    dob = models.DateField(help_text="   Type exactly like: 'YYYY-MM-DD'")
    gender = models.CharField(choices=[('M', 'Male'), ('F','Female'), ('O', 'Other')], max_length=1)
    age = models.IntegerField(default=0)
    count = models.IntegerField(blank=True, default=0) #This field is not used for a "typical" usage

    def __str__(self):
        return self.user.username


class Interest(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    choices = [
        ('Anime', 'Anime'),
        ('K-Pop', 'K-Pop'),
        ('K-Shows', 'K-Shows'),
        ('Webtoon', 'Webtoon'),
        ('American Shows', 'American Shows'),
        ('Movies', 'Movies'),
        ('Food', 'Food'),
        ('Yoga', 'Yoga'),
        ('Working Out', 'Working Out'),
        ('Fighting', 'Fighting'),
        ('Cars', 'Cars'),
        ('Business', 'Business'),
        ('Stocks', 'Stocks'),
        ('School', 'School'),
        ('Relationship', 'Relationship'),
        ('Deep Talks', 'Deep Talks'),
        ('Controversial Subjects', 'Controversial Subjects'),
        ('Video Games', 'Video Games'),
        ('Sports', 'Sports')
    ]
    interest = models.CharField(choices=choices, blank=True, max_length=100)
    
    def __str__(self):
        return f"{self.profile.user.username}: {self.interest}"
    
class ChatRoom(models.Model):
    room_name = models.CharField(max_length=100, primary_key=True)

    def __str__(self):
        return self.room_name
    
class GroupChatRoom(models.Model):
    #id will be the identifier
    num = models.CharField(max_length=100)
    mini = models.IntegerField()
    maxi = models.IntegerField()
    prio = models.CharField(max_length=100)
    npart = models.IntegerField() #number of participants
    interest = models.CharField(max_length=100, blank=True, null=True)

class Participant(models.Model):
    chatRoom = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, blank=True, default=None, null=True)
    groupChatRoom = models.ForeignKey(GroupChatRoom, on_delete=models.CASCADE, blank=True, default=None, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

class Message(models.Model):
    content = models.CharField(max_length=300, blank=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE,default=None)
    chatRoom = models.ForeignKey(ChatRoom, on_delete=models.CASCADE,default=None, blank=True, null=True)
    groupChatRoom = models.ForeignKey(GroupChatRoom, on_delete=models.CASCADE, blank=True, null=True, default=None)
    time = models.DateTimeField(auto_now_add=True)

class Relationship(models.Model):
    profileUser = models.ForeignKey(Profile, related_name="profileUser", on_delete=models.CASCADE)
    profileOther = models.ForeignKey(Profile, related_name="profileOther", on_delete=models.CASCADE)
    choices = [
        ("like", "like"),
        ("not like", "not like"),
    ]
    relationship = models.CharField(blank=True, max_length=30, choices=choices)

    def __str__(self):
        if self.relationship == "like":
            return f"{self.profileUser.user.username} <3 => {self.profileOther.user.username}"
        else:
            return f"{self.profileUser.user.username} X => {self.profileOther.user.username}"




###############################################

class ProfileCreationForm1(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'first_name', 'last_name']

class ProfileCreationForm2(ModelForm):
    class Meta:
        model = Profile
        fields = ['dob', 'gender', 'bio']
        labels = {
            'dob': 'Date of Birth',
        }
        widgets = {
            'bio': Textarea(attrs={'placeholder': 'Tell Everyone About Yourself.'}),
            'dob': DateInput()
        }

class ProfileCreationForm3(ModelForm):
    class Meta:
        model = Profile
        fields = ['ppic1', 'ppic2', 'ppic3', 'ppic4', 'ppic5', 'ppic6']
        labels = {
            'ppic1': 'Choose Up To 5 Photos',
            'ppic2': '',
            'ppic3': '',
            'ppic4': '',
            'ppic5': '',
            'ppic6': '',
        }

match/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import *
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import date
from django.http import JsonResponse
import json
from django.core.paginator import Paginator
# Create your views here.

@login_required
def HomeView(request):
    profile = Profile.objects.get(user=request.user)
    profile.age = (date.today() - profile.dob).days//365
    profile.save()
    interests = Interest.objects.filter(profile=profile)
    context = {
        'profile': profile,
        'interests': interests,
    }
    return render(request, 'match/home.html', context)

def ProfileView(request, username):
    uprofile = Profile.objects.get(user=request.user)
    profile = Profile.objects.get(user__username=username)
    profile.age = (date.today() - profile.dob).days//365
    profile.save()
    interests = Interest.objects.filter(profile=profile)

    relationship12 = Relationship.objects.filter(profileUser=uprofile).filter(profileOther=profile)
    relationship21 = Relationship.objects.filter(profileUser=profile).filter(profileOther=uprofile)
    toChat = False
    if relationship12 and relationship21:
        toChat = True
    context = {
        'profile': profile,
        'interests': interests,
        'uprofile': uprofile,
        'toChat': toChat,
    }
    return render(request, 'match/profile.html', context)

def CreateProfileView(request):
    if request.method == 'POST':
        form1 = ProfileCreationForm1(request.POST)
        form2 = ProfileCreationForm2(request.POST)
        form3 = ProfileCreationForm3(request.FILES)
        n = len(request.FILES)
        if form1.is_valid() and form2.is_valid():
            data1 = form1.cleaned_data
            data2 = form2.cleaned_data
            data3 = request.FILES
            user = User.objects.create_user(data1['username'], data1['email'], data1['password1'])
            user.first_name = data1['first_name']
            user.last_name = data1['last_name']
            user.save()
            profile = Profile(user=user, bio=data2['bio'], 
                              dob=data2['dob'], gender=data2['gender'],
                              age=(date.today() - date(data2['dob'])).days//365)
            profile.ppic1 = data3['ppic1']
            if n>1:
                profile.ppic2 = data3['ppic2']
                if n>2:
                    profile.ppic3 = data3['ppic3']
                    if n>3:
                        profile.ppic4 = data3['ppic4']
                        if n>4:
                            profile.ppic5 = data3['ppic5']
                            if n>5:
                                profile.ppic5 = data3['ppic6']
            profile.save()
            login(request, user)
            return HttpResponseRedirect(reverse('addInterests'))
        else:
            context = {
                'form1': form1,
                'form2': form2,
                'form3': form3,
            }
            return render(request, 'match/createProfile.html', context)
    else:
        form1 = ProfileCreationForm1()
        form2 = ProfileCreationForm2()
        form3 = ProfileCreationForm3()
        context = {
            'form1': form1,
            'form2': form2,
            'form3': form3,
        }
    return render(request, 'match/createProfile.html', context)

def AddInterestsView(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        for choice in request.POST:
            if choice != 'csrfmiddlewaretoken':
                interest = Interest(profile=profile,interest=choice)
                interest.save()
        return HttpResponseRedirect(reverse('HomeView'))
    choices = [ c[1] for c in Interest.interest.field.choices]
    context = {
        'profile': profile,
        'choices': choices,
    }
    return render(request, 'match/addInterests.html', context)

def EditInterestsView(request):
    profile = Profile.objects.get(user=request.user)
    interests = Interest.objects.filter(profile=profile)
    if request.method == 'POST':
        interests.delete()
        for choice in request.POST:
             if choice != 'csrfmiddlewaretoken':
                interest = Interest(profile=profile,interest=choice)
                interest.save()
        return HttpResponseRedirect(reverse('HomeView'))

    interestsList = [i.interest for i in interests]
    print(interestsList)
    choices = [ c[1] for c in Interest.interest.field.choices]
    print(choices)
    context = {
        'profile': profile,
        'choices': choices,
        'interests': interestsList,
    }
    return render(request, 'match/addInterests.html', context)

def ChatView(request, username1, username2):
    uprofile = Profile.objects.get(user=request.user)
    if ChatRoom.objects.filter(room_name=username1+username2):
        print("Chat room found!")
        chatRoom = ChatRoom.objects.get(room_name=username1+username2)
    elif ChatRoom.objects.filter(room_name=username2+username1):
        print("Chat room found, usernames reversed!")
        return HttpResponseRedirect(reverse('chatView', kwargs={'username1': username2, 'username2': username1}))
    else: #Create chat room with username1 as the first one
        chatRoom = ChatRoom(room_name=username1+username2)
        chatRoom.save()
        print("Chat room created!")
    messages = Message.objects.filter(chatRoom=chatRoom)
    ousername = username1 if uprofile.user.username != username1 else username2
    context = {
        'messages': messages,
        'profile': uprofile,
        'ousername': ousername, 
        'room_name': username1+username2,
    }
    return render(request, 'match/chat.html', context)

def ProfileSearchView(request):
    """
    The idea here is that you look at every profile in the platform.
    You can then "like"/"unlike" people while looking at all of their info.
    You will have a list of people that you like, and list you unlike, and filter your search so
        you can see only people you like, unlike, or have not seen yet.
    There is an option to show only people who like you.
    """
    uprofile = Profile.objects.get(user=request.user)
    profiles = Profile.objects.all()
    relationships = Relationship.objects.filter(profileUser=uprofile)
    likes = [ r.profileOther.user.username for r in relationships.filter(relationship="like")]
    unlikes = [ r.profileOther.user.username for r in relationships.filter(relationship="unlike")]

    for profile in profiles:
        profile.age = (date.today() - profile.dob).days//365
        profile.save()

    if request.method == "POST":
        try: #In this case, the user is trying to like/unlike someone
            profileOther = Profile.objects.get(user__username=request.POST['username'])
            if request.POST['relationship'] == 'delete':
                relationship = Relationship.objects.get(profileOther=profileOther)
                relationship.delete()
            else:
                relationship = Relationship(profileUser=uprofile, profileOther=profileOther,
                                            relationship=request.POST['relationship'])
                relationship.save()
            return JsonResponse({'profileUser': relationship.profileUser, 'profileOther': relationship.profileOther,
                                'relationship': relationship.relationship})
        except: #In this case, the user is trying to search/filter their list
            """
            Let's say i have a profileUser already. And I want to get all relationships that associate with the profile:
                relationships = Relationship.objects.filter(profileUser=profileUser)
            Now we want to get all of the relationships in that QuerySet such that "relationship = 'like'"
                relationships = relationships.filter(relationship='like')
            Now we want to get all of the "profileOther" objects from the remaining relationships
                relationships.profileOther
            But now how do we combine the profiles that we filtered from the search: profiles, with the profiles that we-
            -just got from relationships.profileOther?
                profiles = relationships.profileOther & profiles  
            """
            form = request.POST
            if form['search'] != "": 
                profiles = profiles.filter(user__username__icontains=form['search'])
            #In this case, either they are not searcing for a profile, or they are not, so we will filter further
            crelationships = Relationship.objects.filter(profileUser=uprofile)
            match form['filter']:
                case "all": pass
                case 'likes': 
                    #crelationships = crelationships.filter(relationship='like')
                    profilesC = Profile.objects.filter(profileOther__relationship='like').filter(profileOther__profileUser=uprofile)
                    profiles = profilesC & profiles
                case 'unlikes':
                    #crelationships = crelationships.filter(relationship='not like')
                    profilesC = Profile.objects.filter(profileOther__relationship='unlike').filter(profileOther__profileUser=uprofile)
                    profiles = profilesC & profiles
                case 'unseen':
                    """
                    I have all relationships that currently are associated with 'profileUser'. Now how do I find all-
                    -profiles that are not "related" to profileUser?

match/templates/match/addInterests.html
{% extends "base.html" %}

{% load static %}

{% block style %}<link rel="stylesheet" href="{% static 'match/addInterests.css' %}">{% endblock %}

{% block content %}
    <h1>Add interests so you can match with people who have similar taste as you!</h1>
    
    <form method="post">
        {% csrf_token %}
        <div class="form">
            <div class="choices">
                <h2>Choose From:</h2>
                {% for choice in choices %}
                    {% if choice in interests %}
                        
                    {% else %}
                    <div class="choice" id="{{choice}}_id">                        
                        <input class="checkbox" type="checkbox" name="{{choice}}" hidden>
                        <img class="checkImage" src="{% static 'match/addInterestX.png' %}">
                        <label class="choiceLabel">{{choice}}</label>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="chosen">
                <h2>Choosen:</h2>
                {% for choice in choices %}
                    {% if choice in interests %}
                        <div class="choice" id="{{choice}}_id">                        
                            <input class="checkbox" type="checkbox" name="{{choice}}" hidden checked>
                            <img class="checkImage" src="{% static 'match/addInterestX.png' %}">
                            <label class="choiceLabel">{{choice}}</label>
                        </div>
                    {% else %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <input id="button" type="submit" value="Create Interests">
    </form>

    <script src="{% static 'match/addInterests.js' %}"></script>
{% endblock %}

match/templates/match/chat.html
{% extends 'base.html' %}
{% load static %}

{% block style %}<link rel="stylesheet" href="{% static 'match/chat.css' %}">{% endblock %}

{% block content %}
    <p id='room_name' hidden>{{ room_name }}</p>
    <p id="uValue" hidden>{{profile.user.username}}</p>
    <div class="main">
        <div class="left">
            <div id="videos">
                <video id="remoteVideo" autoplay playsinline></video>
                <video id="userVideo" autoplay playsinline></video>
                <div class="type">
                    <label>Type: </label>
                    <input type="text" class="text" placeholder="Send Message...">
                    <input type="submit" class="submit">
                </div>
            </div>
        </div>
        <div class="right">
            
            <div class="chat">
                {% for msg in messages %}
                    <p class="message">[{{msg.time}}] ({{msg.profile.user.username}}): {{ msg.content }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{% static 'match/chat.js' %}"></script>
{% endblock %}

match/templates/match/createProfile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}<link rel="stylesheet" href="{% static 'match/createProfile.css' %}">{% endblock %}


{% block content %}
<h1 class="title">Account Creation</h1>
        <div class="form">
            <div class="left">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form1 %}
                    <span class="labelTag">{{field.label_tag}}</span>
                    <br>
                    {% if field.help_text %}
                        {{field.help_text}}
                        <br>
                    {% endif %}
                    {% if field.errors %}
                        <span style="color: red;">{{field.errors}}</span>
                        <br>
                    {% endif %}
                    <span class="field">{{field}}</span>
                    <br>
                {% endfor %}
                {% for field in form2 %}
                    <span class="labelTag">{{field.label_tag}}</span>
                    <br>
                    {% if field.help_text %}
                        {{field.help_text}}
                        <br>
                    {% endif %}
                    {% if field.errors %}
                        <span style="color: red;">{{field.errors}}</span>
                        <br>
                    {% endif %}
                    <span class="field">{{field}}</span>
                    <br>
                {% endfor %}
            </div>
            <div class="right">
                <p>Add Up To 6 Photos: (At least 1 is required)</p>
                {% for field in form3 %}
                    {% if field.help_text %}
                        {{field.help_text}}
                        <br>
                    {% endif %}
                    {% if field.errors %}
                        <span style="color: red;">{{field.errors}}</span>
                        <br>
                    {% endif %}
                    <span class="fileButton">{{field}}</span>
                {% endfor %}
                <br>
                <p>Your Uploaded Photos: </p>
                <img id="upImage1">
                <img id="upImage2">
                <img id="upImage3">
                <img id="upImage4">
                <img id="upImage5">
                <img id="upImage6">
            </div>
        </div>
            <input type="submit" value="Next" id="submit">
        </form>
        <script src="{% static 'match/createProfile.js' %}"></script>
{% endblock %}

match/templates/match/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}<link rel="stylesheet" href="{% static 'match/profile.css' %}">{% endblock %}

{% block content %}
    <h1>Welcome to Tindeggle!</h1>
    <div class="area">
        <div class="left">
            <img id='img1' src="{{profile.ppic1.url}}">
            {% if profile.ppic2 %}
                <img id='img2' src="{{profile.ppic2.url}}">
            {% endif %}
            {% if profile.ppic3 %}
                <img id='img3' src="{{profile.ppic3.url}}">
            {% endif %}
            {% if profile.ppic4 %}
                <img id='img4' src="{{profile.ppic4.url}}">
            {% endif %}
            {% if profile.ppic5 %}
                <img id='img5' src="{{profile.ppic5.url}}">
            {% endif %}
            {% if profile.ppic6 %}
                <img id='img6' src="{{profile.ppic6.url}}">
            {% endif %}
        </div>
        <div class="right">
            <p><b>Username:</b> {{profile.user.username}}</p>
            <p><b>Name:</b> {{profile.user.first_name}} {{profile.user.last_name}}</p>
            <p><b>Birthday:</b> {{profile.dob}}</p>
            <p><b>Age:</b> {{profile.age}}</p>
            <p><b>Bio:</b>{{profile.bio}}</p>
            <div class="interests">
                <p><b>Interests:</b> </p>
                {% for int in interests %}
                    <p class="interest">{{int.interest}}</p>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

match/templates/match/profile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}<link rel="stylesheet" href="{% static 'match/profile.css' %}">{% endblock %}

{% block content %}
    <div class="startChat">
        {% if toChat %}
            <button>
                Start Chat
            </button>
        {% else %}
            <button disabled>
                Start Chat
            </button>
        {% endif %}
    </div>
    <div class="area">
        <div class="left">
            <img id='img1' src="{{profile.ppic1.url}}">
            {% if profile.ppic2 %}
                <img id='img2' src="{{profile.ppic2.url}}">
            {% endif %}
            {% if profile.ppic3 %}
                <img id='img3' src="{{profile.ppic3.url}}">
            {% endif %}
            {% if profile.ppic4 %}
                <img id='img4' src="{{profile.ppic4.url}}">
            {% endif %}
            {% if profile.ppic5 %}
                <img id='img5' src="{{profile.ppic5.url}}">
            {% endif %}
            {% if profile.ppic6 %}
                <img id='img6' src="{{profile.ppic6.url}}">
            {% endif %}
        </div>
        <div class="right">
            <p><b>Username:</b> {{profile.user.username}}</p>
            <p><b>Name:</b> {{profile.user.first_name}} {{profile.user.last_name}}</p>
            <p><b>Birthday:</b> {{profile.dob}}</p>
            <p><b>Age:</b> {{profile.age}}</p>
            <p><b>Bio:</b>{{profile.bio}}</p>
            <div class="interests">
                <p><b>Interests:</b> </p>
                {% for int in interests %}
                    <p class="interest">{{int.interest}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <script>
        let button = document.querySelector('button');

        button.addEventListener('click', ()=>{
            window.location.pathname = 'chat/' + "{{uprofile.user.username}}" + '/' + 
                                        "{{profile.user.username}}" + '/'
        })
    </script>
{% endblock %}

match/templates/match/profileSearch.html
{% extends "base.html" %}

{% load static %}

{% block style %}<link rel="stylesheet" href="{% static 'match/profileSearch.css' %}">{% endblock %}

{% block content %}
    <a href="{% url 'HomeView' %}">Home Page</a>
    <h1>Profile Search</h1>
    <form method="post">
        {% csrf_token %}
        <input type="search" name="search">
        <select id="filter" name="filter">
            <option value="all">View All Profiles</option>
            <option value="likes">Your Likes</option>
            <option value="unlikes">Your Unlikes</option>
            <option value="unseen">Not Seen</option>
            <option value="liked">Liked By</option>
        </select>
        <input type="submit" value="Search">
    </form>

    {% for profile in page_obj %}
        {% if profile == uprofile %}
        {% else %}
            <div class="profile">
                <a href="{% url 'profileView' profile.user.username %}"><img width="200" height="200" class="profilePic" src="{{profile.ppic1.url}}"></a>
                <div class="right">
                    <div class="small">
                        <div>
                            <h4>Username</h4>
                            <h3 class="username">{{profile.user.username}}</h3>
                        </div>
                        <div>
                            <h4>First Name</h4>
                            <h3>{{profile.user.first_name}}</h3>
                        </div>
                        <div>
                            <h4>Age</h4>
                            <h3>{{profile.age}}</h3>
                        </div>
                        <div>
                            <h4>Gender</h4>
                            <h3>{{profile.gender}}</h3>
                        </div>
                    </div>
                    <div class="interests">
                        <p>Interests:</p>
                        {% for interest in profile.interest_set.all %}
                            {% if interest.interest in uinterests %}
                                <p class="same">{{ interest.interest }}</p>
                            {% else %}
                                <p class="diff">{{ interest.interest }}</p>
                            {% endif %}
                        {% empty %}
                        {% endfor %}
                    </div>
                    <div class="bio">
                        <p><b>Bio:</b></p>
                        <p>{{profile.bio}}</p>
                    </div>
                </div>
                <div class="buttons">
                    <form method="post">
                        {% csrf_token %}
                        {% if profile.user.username in likes %}
                            <div class="likeDiv" hidden>
                                <input class='like' type="radio" value="like" name="{{profile.user.username}}" hidden>
                                <label>Like</label>
                            </div>
                            <div class="unlikeDiv" hidden>
                                <input class="unlike" type="radio" value="unlike" name="{{profile.user.username}}" hidden>
                                <label>Not Like</label>
                            </div>
                            <div class="undoLike">
                                <label>Undo Like</label>
                            </div>
                            <div class="undoNotLike" hidden>
                                <label>Undo Not Like</label>
                            </div>
                        {% elif profile.user.username in unlikes %}
                            <div class="likeDiv" hidden>
                                <input class='like' type="radio" value="like" name="{{profile.user.username}}" hidden>
                                <label>Like</label>
                            </div>
                            <div class="unlikeDiv" hidden>
                                <input class="unlike" type="radio" value="unlike" name="{{profile.user.username}}" hidden>
                                <label>Not Like</label>
                            </div>
                            <div class="undoLike" hidden>
                                <label>Undo Like</label>
                            </div>
                            <div class="undoNotLike">
                                <label>Undo Not Like</label>
                            </div>
                        {% else %}
                            <div class="likeDiv">
                                <input class='like' type="radio" value="like" name="{{profile.user.username}}" hidden>
                                <label>Like</label>
                            </div>
                            <div class="unlikeDiv">
                                <input class="unlike" type="radio" value="unlike" name="{{profile.user.username}}" hidden>
                                <label>Not Like</label>
                            </div>
                            <div class="undoLike" hidden>
                                <label>Undo Like</label>
                            </div>
                            <div class="undoNotLike" hidden>
                                <label>Undo Not Like</label>
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        {% endif %}
    {% endfor %}


    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


    <script src="{% static 'match/profileSearch.js' %}"></script>
{% endblock %}